# Generated by Django 2.0.7 on 2021-07-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=60)),
                ('last_name', models.CharField(blank=True, default='', max_length=60)),
                ('email', models.TextField(blank=True, default='', max_length=300)),
                ('username', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
    ]
