# Generated by Django 2.1.5 on 2021-07-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefixes',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mr', 'Mr'), ('Mrs', 'Mrs')], default='', max_length=60),
        ),
    ]
