# Generated by Django 2.1.5 on 2021-07-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210722_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefixes',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Ms', 'Ms')], default='', max_length=60),
        ),
    ]
