# Generated by Django 2.1.5 on 2021-07-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210722_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefixes',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mr', 'Mr')], default='', max_length=60),
        ),
    ]
