# Generated by Django 2.1.5 on 2021-07-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210729_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefixes',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], default='', max_length=60),
        ),
    ]
