# Generated by Django 2.1.5 on 2021-07-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210722_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('drinks', 'drinks'), ('appetizers', 'appetizers'), ('treats', 'treats'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
