# Generated by Django 2.1.5 on 2021-07-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=9000)),
                ('course_number', models.IntegerField(default=0, max_length=60)),
                ('instructor_name', models.CharField(default='', max_length=128)),
                ('duration', models.FloatField(default='', max_length=128)),
            ],
        ),
    ]
